### ISSUE TITLE
Not working on TAS-268

### ISSUE THREAD

**Issue by shingoxray** [OneCDOnly/create-autorun#15]
End with the following output:
```
info: NAS model: TAS-268
info: QTS version: 4.3.3 #20220303
info: default volume: /share/CACHEDEV1_DATA
info: autorun partition should be: /dev/mtd6
skip: unable to ubiattach 'ubiattach: error!: UBI is not present in the system'
info: will try as ext4 instead
done: mounted ext4 autorun partition: /dev/mtd6 -> /tmp/create-autorun.GKSQvl
fail: Partition tag-file not found
done: unmounted ext4 autorun partition
ubidetach: error!: UBI is not present in the system
```

**Comment by OneCDOnly** [comment]
Hi @shingoxray , I apologise for the delay in responding. 

Can you please run the following commands, then post the results back here? 
```
mkdir /tmp/tas
mount -t ext4 /dev/mmcblk0p7 /tmp/tas
ll /tmp/tas
umount /tmp/tas
```
Let's see if we can locate a tag-file suited to your NAS model.

**Comment by hyhkjiy** [comment]
Hello @OneCDOnly, I got same result on TS-228:
```
[/share/CACHEDEV1_DATA/homes/admin/scripts] # ./create-autorun.sh
create-autorun.sh 230319

info: NAS model: TS-228
info: QTS version: 4.3.6 #20221124
info: default volume: /share/CACHEDEV1_DATA
info: autorun partition should be: /dev/mtd6
skip: unable to ubiattach 'ubiattach: error!: UBI is not present in the system'
info: will try as ext4 instead
done: mounted ext4 autorun partition: /dev/mtd6 -> /tmp/create-autorun.cDkzdg
fail: Partition tag-file not found
done: unmounted ext4 autorun partition
ubidetach: error!: UBI is not present in the system
```

These are the files of  /dev/mmcblk0p7:
```
[/share/CACHEDEV1_DATA/homes/admin/scripts] # mkdir /tmp/tas
[/share/CACHEDEV1_DATA/homes/admin/scripts] # mount -t ext4 /dev/mmcblk0p7 /tmp/tas
[/share/CACHEDEV1_DATA/homes/admin/scripts] # ll /tmp/tas
drwxr-xr-x    3 admin    administ      4.0k May 26 02:08 ./
drwxrwxrwx   21 admin    administ      2.0k May 26 11:39 ../
-rwxr-xr-x    1 admin    administ     22.7k Jan 31  2019 K018backup_conf.sh*
-rwxr-xr-x    1 admin    administ        11 Jan 14  2019 K01PYSmtbEex.sh*
-rwxr-xr-x    1 admin    administ        11 Jan 14  2019 autorun.sh*
drwx------    2 admin    administ      4.0k Jan  1  1970 lost+found/
-rw-r--r--    1 admin    administ         0 Nov 16  2015 null_file
[/share/CACHEDEV1_DATA/homes/admin/scripts] # umount /tmp/tas
```

**Comment by OneCDOnly** [comment]
Thanks @hyhkjiy, that helps. 👍🏽 

I'm not sure how reliable an indicator those files will be though.

Maybe I should remove the "tag-file" check from `create-autorun.sh`? It's not absolutely necessary. 

Thoughts please?

**Comment by hyhkjiy** [comment]
Sorry @OneCDOnly , I can't give valid advice because I am not familiar with QNAP systems and I have not used other models of QNAP NAS.

But I agree with your point about removing the "tag file" check. I think the partition to be mount should be decided in the DetermineAutorunPartitionLocation() function, depending on the NAS model. For temporarily unsupported models, maybe you can just report an error in the DetermineAutorunPartitionLocation() function.

Here are some information that may be useful: https://wiki.qnap.com/wiki/Running_Your_Own_Application_at_Startup

Hope can help you!

**Comment by OneCDOnly** [comment]
@hyhkjiy cheers mate. 

I've decided to leave the tag-file check but make it a non-fatal error when the tag-file can't be found.

**Comment by OneCDOnly** [comment]
I've just pushed an updated script. Can you guys please try it out?

**Comment by hyhkjiy** [comment]
Greetings @OneCDOnly, I just tried the latest code.

As you said, no more fatal errors are generated where the tag-file is detected. This is great!

But the autorun.sh file still doesn't work on my device.It looks like it has something to do with permissions, here's the relevant log:
```
[/share/homes/admin/scripts] # ./create-autorun.sh
create-autorun.sh 230527

info: NAS model: TS-228
info: QTS version: 4.3.6 #20221124
info: default volume: /share/CACHEDEV1_DATA
info: autorun partition should be: /dev/mtd6
skip: unable to ubiattach
info: will try as: ext4 instead
done: mounted: ext4 device: /dev/mmcblk0p7 -> /tmp/create-autorun.1Tsbob
info: partition tag-file not found
skip: autorun.sh already exists: /share/CACHEDEV1_DATA/.system/autorun/autorun.sh
ln: /tmp/create-autorun.1Tsbob/autorun.sh: File exists
fail: Unable to create symlink
done: unmounted ext4 autorun partition
(reverse-i-search)`': rm create-autorun.sh
[/share/homes/admin/scripts] # mount -text4 /dev/mmcblk0p7 /tmp/config/
[/share/homes/admin/scripts] # ll /tmp/config/
drwxr-xr-x    3 admin    administ      4.0k May 26 16:35 ./
drwxrwxrwx   20 admin    administ      1.8k May 28 22:55 ../
-rwxr-xr-x    1 admin    administ     22.7k Jan 31  2019 K018backup_conf.sh*
-rwxr-xr-x    1 admin    administ        11 Jan 14  2019 K01PYSmtbEex.sh*
-rwxr-xr-x    1 admin    administ        11 Jan 14  2019 autorun.sh*
drwx------    2 admin    administ      4.0k Jan  1  1970 lost+found/
-rw-r--r--    1 admin    administ         0 Nov 16  2015 null_file
[/share/homes/admin/scripts] # echo "echo 1" >> /tmp/config/autorun.sh
-sh: /tmp/config/autorun.sh: Permission denied
[/share/homes/admin/scripts] # chmod 777 /tmp/config/autorun.sh
chmod: /tmp/config/autorun.sh: Operation not permitted
[/share/homes/admin/scripts] # umount /tmp/config/
[/share/homes/admin/scripts] # whoami
admin
[/share/homes/admin/scripts] # groups
administrators
```

I also tried mounting the partition with the rw parameter, but the autorun.sh file is always in onlyread mode, even though the result of the ll command indicates that it can be written by the creator.

This is really giving me a headache and I would appreciate if you could give me some advice.

**Comment by OneCDOnly** [comment]
I wonder if your existing autorun.sh file has the immutable bit set? 

With your partition mounted, please check this with: 
```
lsattr /tmp/config/autorun.sh
```

**Comment by hyhkjiy** [comment]
Please accept my most sincere thanks @OneCDOnly! Your help made me solve this problem.

I used the lsattr command after mounting the partition and got the following results:
```
# lsattr /tmp/config/autorun.sh
-----ia-A---- /tmp/config/autorun.sh
```

This means that immutable and append-only restrictions have been added to the file.
I ran create-autorun.sh again after using chattr to lift these restrictions, and then I got the correct autorun.sh link file and scripts directory. Then I added a test script to the scripts directory, and restarted the device, which ran the test script perfectly after the restart.

This means I can do more with my NAS, and this repository is really a great project!

**Comment by OneCDOnly** [comment]
Cheers @hyhkjiy, glad it's working for you. 👍🏽

**Comment by shingoxray** [comment]
> 

Sorry for the late reply. Results:
```shell
[~] # mkdir /tmp/tas
[~] # mount -t ext4 /dev/mmcblk0p7 /tmp/tas
[~] # ll /tmp/tas
drwxr-xr-x    3 admin    administ      4.0k May 27 18:52 ./
drwxrwxrwx   22 admin    administ      2.1k May 30 23:46 ../
-rwxr-xr-x    1 admin    administ       207 Aug 27  2018 autorun.sh*
drwx------    2 admin    administ      4.0k Jan  1  1970 lost+found/
-rw-r--r--    1 admin    administ         0 Jun 16  2015 null_file
[~] # umount /tmp/tas
[~] #
```

**Comment by OneCDOnly** [comment]
No worries @shingoxray . 👍🏽 

It looks like the correct location. You already have an `autorun.sh` file there, so that's a good sign. I'm guessing it's probably immutable like @hyhkjiy's was earlier in this topic. 

Can you please display the contents of that `autorun.sh`? 
```
cat /tmp/tas/autorun.sh
```
... then post it back here? I'm curious as to why your NAS already has an autorun. 

Then try renaming that file as a backup, so we can create a new `autorun.sh`
```
mv /tmp/tas/autorun.sh /tmp/tas/autorun.bak
```

**Comment by OneCDOnly** [comment]
If you're unable to rename your `autorun.sh` due to a permissions error, please try disabling the immutable bit, then give renaming another go:
```
chattr -i /tmp/tas/autorun.sh
```

**Comment by shingoxray** [comment]
I did this by myself a long time ago, following QNAP's guide.
It worked by removing the existing ```autorun.sh``` . Thanks!
